<?php
class CheckLoginController extends \Think\Controller {
    public function __construct() {
        parent::__construct(); // TODO: Change the autogenerated stub
        if (empty($_SESSION['admin'])) {
            $url = U("Admin/Index/index");
            //重定向到指定的URL地址
            redirect($url, 0, '');

        }
    }

}