<?php
class CheckLoginController extends \Think\Controller {
    public function __construct() {
        parent::__construct();
        // TODO: Change the autogenerated stub
        if (empty($_SESSION['username'])) {
            $url = U("Index/userLogin");
            //重定向到指定的URL地址
            redirect($url, 0, '亲爱的访客，请您先登录体验完整功能');
        }
    }

}